// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Brand struct {
	IDBrand   int32
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}

type BrandImage struct {
	IDImg   string
	IDBrand int32
}

type Cart struct {
	IDCart    int32
	Uuid      string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}

type CartItem struct {
	IDCartItem int32
	IDCart     int32
	IDProduct  string
	Quantity   int32
	CreatedAt  time.Time
	UpdatedAt  sql.NullTime
	DeletedAt  sql.NullTime
}

type Category struct {
	IDCate      int32
	Name        string
	Description sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type Coupon struct {
	IDCoupon      int32
	Code          string
	Type          string
	Discount      string
	MinOrderValue string
	MaxUser       int32
	UsedCount     int32
	ExpiredAt     time.Time
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	DeletedAt     sql.NullTime
}

type Image struct {
	IDImg     string
	Path      string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}

type Notification struct {
	IDNotifi    string
	Title       sql.NullString
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type ORDER struct {
	IDOrder       string
	IDStatus      int32
	Uuid          string
	IDPayment     int32
	IDShopOwner   int32
	ShippingFee   sql.NullString
	Total         sql.NullString
	PaymentStatus sql.NullString
	CreatedAt     sql.NullTime
	CanceledAt    sql.NullTime
	CompletedAt   sql.NullTime
	DeliveryAt    sql.NullTime
}

type OauthAccount struct {
	ID           int64
	Uuid         string
	Provider     string
	ProviderID   string
	AccessToken  sql.NullString
	RefreshToken sql.NullString
	ExpiredAt    sql.NullTime
	CreatedAt    time.Time
	UpdatedAt    sql.NullTime
}

type OrderCoupon struct {
	IDOrder  string
	IDCoupon int32
}

type OrderDetail struct {
	IDOrder   string
	IDProduct string
	Price     string
	Quantity  int32
	CreatedAt time.Time
}

type PaymentMethod struct {
	IDPayment   int32
	Name        string
	Description sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type Permission struct {
	ActionID    int32
	ActionName  string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type Product struct {
	IDProduct   string
	IDBrand     int32
	IDSubCate   int32
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type ProductDetail struct {
	IDProduct      string
	Price          string
	LikeCount      int32
	Quantity       int32
	ProductionDate sql.NullTime
	ExpirationDate sql.NullTime
	UpdatedAt      sql.NullTime
}

type ProductImage struct {
	IDProduct string
	IDImg     string
}

type RefreshToken struct {
	ID        int64
	Uuid      string
	Token     string
	ExpiredAt time.Time
	CreatedAt sql.NullTime
}

type Review struct {
	IDReview  int32
	Uuid      string
	IDProduct string
	Rating    int16
	Comment   sql.NullString
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}

type Role struct {
	RoleID      int32
	RoleName    string
	Description sql.NullString
}

type RolePermission struct {
	ActionID  int32
	RoleID    int32
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}

type ShopOwner struct {
	IDShopOwner int32
	Uuid        string
	Name        string
	Description sql.NullString
	AvatarUrl   sql.NullString
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type ShopOwnerNotification struct {
	IDNotifi    string
	IDShopOwner int32
	IsRead      bool
	CreatedAt   time.Time
}

type Status struct {
	IDStatus    int32
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type SubCategory struct {
	IDSubCate   int32
	IDCate      int32
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type USER struct {
	Uuid         string
	IDStatus     sql.NullInt32
	UserName     string
	DateOfBirth  sql.NullTime
	Email        string
	PhoneNum     sql.NullString
	Address      sql.NullString
	PasswordHash string
	AvatarUrl    sql.NullString
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullTime
}

type UserActivityLog struct {
	Uuid      string
	ActionID  int32
	Resource  sql.NullString
	IpAddress sql.NullString
	UserAgent sql.NullString
	Metadata  pqtype.NullRawMessage
	CreatedAt time.Time
}

type UserNotification struct {
	Uuid      string
	IDNotifi  string
	IsRead    bool
	CreatedAt time.Time
}

type UserPaymentMethod struct {
	ID            int32
	Uuid          string
	IDPayment     int32
	AccountNumber string
	IsDefault     bool
	CreatedAt     time.Time
	UpdatedAt     sql.NullTime
	DeletedAt     sql.NullTime
}

type UserRole struct {
	RoleID int32
	Uuid   string
}
