// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package database

import (
	"context"
	"database/sql"
)

const createPermission = `-- name: CreatePermission :exec
INSERT INTO permissions(action_name, description) VALUES($1,$2) RETURNING action_id
`

type CreatePermissionParams struct {
	ActionName  string
	Description sql.NullString
}

// _______________ Bảng permissions 2 ___________________
func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) error {
	_, err := q.db.ExecContext(ctx, createPermission, arg.ActionName, arg.Description)
	return err
}

const createRole = `-- name: CreateRole :exec
INSERT INTO role(role_name,description) VALUES($1,$2) RETURNING role_id
`

type CreateRoleParams struct {
	RoleName    string
	Description sql.NullString
}

// _______________ Bảng Role 1 ___________________
func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) error {
	_, err := q.db.ExecContext(ctx, createRole, arg.RoleName, arg.Description)
	return err
}

const createRolePermission = `-- name: CreateRolePermission :exec
INSERT INTO role_permission(action_id, role_id) VALUES($1,$2)
`

type CreateRolePermissionParams struct {
	ActionID int32
	RoleID   int32
}

// _______________ Bảng Role_Permissions 3 ___________________
func (q *Queries) CreateRolePermission(ctx context.Context, arg CreateRolePermissionParams) error {
	_, err := q.db.ExecContext(ctx, createRolePermission, arg.ActionID, arg.RoleID)
	return err
}

const createStatus = `-- name: CreateStatus :exec

INSERT INTO status(name,description,updated_at,deleted_at) VALUES($1,$2,$3,$4) RETURNING id_status
`

type CreateStatusParams struct {
	Name        string
	Description sql.NullString
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

// // File: sql/queries.sql: tệp tin này chủ yếu chứa các câu lệnh thực thi
// _______________ Bảng Status 0 ___________________
func (q *Queries) CreateStatus(ctx context.Context, arg CreateStatusParams) error {
	_, err := q.db.ExecContext(ctx, createStatus,
		arg.Name,
		arg.Description,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO "USER"(id_status, user_name,date_of_birth, email, phone_num, address, password_hash, avatar_url)
VALUES($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateUserParams struct {
	IDStatus     sql.NullInt32
	UserName     string
	DateOfBirth  sql.NullTime
	Email        string
	PhoneNum     sql.NullString
	Address      sql.NullString
	PasswordHash string
	AvatarUrl    sql.NullString
}

// _______________ Bảng User 4 ___________________
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.IDStatus,
		arg.UserName,
		arg.DateOfBirth,
		arg.Email,
		arg.PhoneNum,
		arg.Address,
		arg.PasswordHash,
		arg.AvatarUrl,
	)
	return err
}

const createUserRole = `-- name: CreateUserRole :exec
INSERT INTO user_role(uuid, role_id) VALUES($1, $2)
`

type CreateUserRoleParams struct {
	Uuid   string
	RoleID int32
}

// _______________ Bảng User-Roles 5 ___________________
func (q *Queries) CreateUserRole(ctx context.Context, arg CreateUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, createUserRole, arg.Uuid, arg.RoleID)
	return err
}

const deletePermission = `-- name: DeletePermission :execresult
DELETE FROM permissions WHERE action_id = $1
`

func (q *Queries) DeletePermission(ctx context.Context, actionID int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deletePermission, actionID)
}

const deleteRole = `-- name: DeleteRole :execresult
DELETE FROM role WHERE role_id = $1
`

func (q *Queries) DeleteRole(ctx context.Context, roleID int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteRole, roleID)
}

const deleteRolePermission = `-- name: DeleteRolePermission :execresult
DELETE FROM role_permission WHERE action_id = $1 AND role_id = $2
`

type DeleteRolePermissionParams struct {
	ActionID int32
	RoleID   int32
}

func (q *Queries) DeleteRolePermission(ctx context.Context, arg DeleteRolePermissionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteRolePermission, arg.ActionID, arg.RoleID)
}

const deleteStatus = `-- name: DeleteStatus :execresult
DELETE FROM status WHERE id_status = $1
`

func (q *Queries) DeleteStatus(ctx context.Context, idStatus int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteStatus, idStatus)
}

const deleteUser = `-- name: DeleteUser :execresult
DELETE FROM "USER" WHERE uuid = $1
`

func (q *Queries) DeleteUser(ctx context.Context, uuid string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteUser, uuid)
}

const deleteUserRole = `-- name: DeleteUserRole :exec
DELETE FROM user_role WHERE uuid = $1 AND role_id = $2
`

type DeleteUserRoleParams struct {
	Uuid   string
	RoleID int32
}

func (q *Queries) DeleteUserRole(ctx context.Context, arg DeleteUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserRole, arg.Uuid, arg.RoleID)
	return err
}

const getAllPermissions = `-- name: GetAllPermissions :many
SELECT action_id, action_name, description, created_at, updated_at, deleted_at FROM permissions
`

func (q *Queries) GetAllPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, getAllPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ActionID,
			&i.ActionName,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllRoles = `-- name: GetAllRoles :many
SELECT role_id, role_name, description FROM role
`

func (q *Queries) GetAllRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, getAllRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.RoleID, &i.RoleName, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllStatus = `-- name: GetAllStatus :many
SELECT id_status, name, description, created_at, updated_at, deleted_at FROM status
`

func (q *Queries) GetAllStatus(ctx context.Context) ([]Status, error) {
	rows, err := q.db.QueryContext(ctx, getAllStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Status
	for rows.Next() {
		var i Status
		if err := rows.Scan(
			&i.IDStatus,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT uuid, id_status, user_name, date_of_birth, email, phone_num, address, password_hash, avatar_url, created_at, updated_at, deleted_at FROM "USER"
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]USER, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []USER
	for rows.Next() {
		var i USER
		if err := rows.Scan(
			&i.Uuid,
			&i.IDStatus,
			&i.UserName,
			&i.DateOfBirth,
			&i.Email,
			&i.PhoneNum,
			&i.Address,
			&i.PasswordHash,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPermissionByID = `-- name: GetPermissionByID :one
SELECT action_id, action_name, description, created_at, updated_at, deleted_at FROM permissions WHERE action_id = $1
`

func (q *Queries) GetPermissionByID(ctx context.Context, actionID int32) (Permission, error) {
	row := q.db.QueryRowContext(ctx, getPermissionByID, actionID)
	var i Permission
	err := row.Scan(
		&i.ActionID,
		&i.ActionName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPermissionsByRoleID = `-- name: GetPermissionsByRoleID :many
SELECT p.action_id, p.action_name, p.description
FROM role r 
	INNER JOIN role_permission rp ON r.role_id = rp.role_id
	INNER JOIN permissions p ON p.action_id = rp.action_id
WHERE r.role_id = $1
`

type GetPermissionsByRoleIDRow struct {
	ActionID    int32
	ActionName  string
	Description sql.NullString
}

func (q *Queries) GetPermissionsByRoleID(ctx context.Context, roleID int32) ([]GetPermissionsByRoleIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getPermissionsByRoleID, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPermissionsByRoleIDRow
	for rows.Next() {
		var i GetPermissionsByRoleIDRow
		if err := rows.Scan(&i.ActionID, &i.ActionName, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT role_id, role_name, description FROM role WHERE role_id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, roleID int32) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByID, roleID)
	var i Role
	err := row.Scan(&i.RoleID, &i.RoleName, &i.Description)
	return i, err
}

const getRolesByPermissionID = `-- name: GetRolesByPermissionID :many
SELECT r.role_id, r.role_name, r.description
FROM role r 
	INNER JOIN role_permission rp ON r.role_id = rp.role_id
	INNER JOIN permissions p ON p.action_id = rp.action_id
WHERE p.action_id = $1
`

func (q *Queries) GetRolesByPermissionID(ctx context.Context, actionID int32) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, getRolesByPermissionID, actionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.RoleID, &i.RoleName, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRolesByUserID = `-- name: GetRolesByUserID :many
SELECT r.role_id, r.role_name, r.description
FROM "USER" u 
	JOIN user_role ur ON u.uuid = ur.uuid 
	JOIN role r ON r.role_id = ur.role_id
	WHERE u.uuid = $1
`

func (q *Queries) GetRolesByUserID(ctx context.Context, uuid string) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, getRolesByUserID, uuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.RoleID, &i.RoleName, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatusByID = `-- name: GetStatusByID :one
SELECT id_status, name, description, created_at, updated_at, deleted_at FROM status WHERE id_status = $1
`

func (q *Queries) GetStatusByID(ctx context.Context, idStatus int32) (Status, error) {
	row := q.db.QueryRowContext(ctx, getStatusByID, idStatus)
	var i Status
	err := row.Scan(
		&i.IDStatus,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUID_PasswordHashByEmail = `-- name: GetUID_PasswordHashByEmail :one
SELECT uuid, password_hash FROM "USER" WHERE email = $1
`

type GetUID_PasswordHashByEmailRow struct {
	Uuid         string
	PasswordHash string
}

func (q *Queries) GetUID_PasswordHashByEmail(ctx context.Context, email string) (GetUID_PasswordHashByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUID_PasswordHashByEmail, email)
	var i GetUID_PasswordHashByEmailRow
	err := row.Scan(&i.Uuid, &i.PasswordHash)
	return i, err
}

const getUID_PasswordHashByPhone = `-- name: GetUID_PasswordHashByPhone :one
SELECT uuid, password_hash FROM "USER" WHERE phone_num = $1
`

type GetUID_PasswordHashByPhoneRow struct {
	Uuid         string
	PasswordHash string
}

func (q *Queries) GetUID_PasswordHashByPhone(ctx context.Context, phoneNum sql.NullString) (GetUID_PasswordHashByPhoneRow, error) {
	row := q.db.QueryRowContext(ctx, getUID_PasswordHashByPhone, phoneNum)
	var i GetUID_PasswordHashByPhoneRow
	err := row.Scan(&i.Uuid, &i.PasswordHash)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT uuid, id_status, user_name, date_of_birth, email, phone_num, address, password_hash, avatar_url, created_at, updated_at, deleted_at FROM "USER" WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (USER, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i USER
	err := row.Scan(
		&i.Uuid,
		&i.IDStatus,
		&i.UserName,
		&i.DateOfBirth,
		&i.Email,
		&i.PhoneNum,
		&i.Address,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT uuid, id_status, user_name, date_of_birth, email, phone_num, address, password_hash, avatar_url, created_at, updated_at, deleted_at FROM "USER" WHERE uuid = $1
`

func (q *Queries) GetUserByID(ctx context.Context, uuid string) (USER, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, uuid)
	var i USER
	err := row.Scan(
		&i.Uuid,
		&i.IDStatus,
		&i.UserName,
		&i.DateOfBirth,
		&i.Email,
		&i.PhoneNum,
		&i.Address,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT uuid, id_status, user_name, date_of_birth, email, phone_num, address, password_hash, avatar_url, created_at, updated_at, deleted_at FROM "USER" WHERE phone_num = $1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phoneNum sql.NullString) (USER, error) {
	row := q.db.QueryRowContext(ctx, getUserByPhone, phoneNum)
	var i USER
	err := row.Scan(
		&i.Uuid,
		&i.IDStatus,
		&i.UserName,
		&i.DateOfBirth,
		&i.Email,
		&i.PhoneNum,
		&i.Address,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByRoleID = `-- name: GetUserByRoleID :many
SELECT u.uuid, u.user_name, u.email, u.phone_num, u.address
FROM "USER" u 
	JOIN user_role ur ON u.uuid = ur.uuid 
	JOIN role r ON r.role_id = ur.role_id
	WHERE r.role_id = $1
`

type GetUserByRoleIDRow struct {
	Uuid     string
	UserName string
	Email    string
	PhoneNum sql.NullString
	Address  sql.NullString
}

func (q *Queries) GetUserByRoleID(ctx context.Context, roleID int32) ([]GetUserByRoleIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserByRoleID, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserByRoleIDRow
	for rows.Next() {
		var i GetUserByRoleIDRow
		if err := rows.Scan(
			&i.Uuid,
			&i.UserName,
			&i.Email,
			&i.PhoneNum,
			&i.Address,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerUser = `-- name: RegisterUser :exec
INSERT INTO "USER"(id_status, user_name,date_of_birth, email, phone_num, address, password_hash, avatar_url)
VALUES(2, 	/*Mặc định là client thông thường*/
	$1, $2, $3, $4, $5, $6, $7)
`

type RegisterUserParams struct {
	UserName     string
	DateOfBirth  sql.NullTime
	Email        string
	PhoneNum     sql.NullString
	Address      sql.NullString
	PasswordHash string
	AvatarUrl    sql.NullString
}

func (q *Queries) RegisterUser(ctx context.Context, arg RegisterUserParams) error {
	_, err := q.db.ExecContext(ctx, registerUser,
		arg.UserName,
		arg.DateOfBirth,
		arg.Email,
		arg.PhoneNum,
		arg.Address,
		arg.PasswordHash,
		arg.AvatarUrl,
	)
	return err
}

const updatePermission_PATCH = `-- name: UpdatePermission_PATCH :execresult
UPDATE permissions SET 
	action_name = COALESCE($1, action_name), 
	description = COALESCE($2, description), 
	updated_at = NOW()
WHERE action_id = $3
`

type UpdatePermission_PATCHParams struct {
	ActionName  string
	Description sql.NullString
	ActionID    int32
}

func (q *Queries) UpdatePermission_PATCH(ctx context.Context, arg UpdatePermission_PATCHParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updatePermission_PATCH, arg.ActionName, arg.Description, arg.ActionID)
}

const updatePermission_PUT = `-- name: UpdatePermission_PUT :execresult
UPDATE permissions SET action_name = $1, description = $2, updated_at = NOW() WHERE action_id = $3
`

type UpdatePermission_PUTParams struct {
	ActionName  string
	Description sql.NullString
	ActionID    int32
}

func (q *Queries) UpdatePermission_PUT(ctx context.Context, arg UpdatePermission_PUTParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updatePermission_PUT, arg.ActionName, arg.Description, arg.ActionID)
}

const updateRolePermissionByRoleID_PUT = `-- name: UpdateRolePermissionByRoleID_PUT :execresult
UPDATE role_permission 
	SET action_id = $1, 
	role_id = $2,
	updated_at = NOW() 
WHERE action_id = $1 AND role_id = $2
`

type UpdateRolePermissionByRoleID_PUTParams struct {
	ActionID int32
	RoleID   int32
}

func (q *Queries) UpdateRolePermissionByRoleID_PUT(ctx context.Context, arg UpdateRolePermissionByRoleID_PUTParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateRolePermissionByRoleID_PUT, arg.ActionID, arg.RoleID)
}

const updateRole_PATCH = `-- name: UpdateRole_PATCH :execresult
UPDATE role SET role_name = COALESCE($1, role_name), description = COALESCE($2, description) WHERE role_id = $3
`

type UpdateRole_PATCHParams struct {
	RoleName    string
	Description sql.NullString
	RoleID      int32
}

func (q *Queries) UpdateRole_PATCH(ctx context.Context, arg UpdateRole_PATCHParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateRole_PATCH, arg.RoleName, arg.Description, arg.RoleID)
}

const updateRole_PUT = `-- name: UpdateRole_PUT :execresult
UPDATE role SET role_name = $1, description = $2 WHERE role_id = $3
`

type UpdateRole_PUTParams struct {
	RoleName    string
	Description sql.NullString
	RoleID      int32
}

func (q *Queries) UpdateRole_PUT(ctx context.Context, arg UpdateRole_PUTParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateRole_PUT, arg.RoleName, arg.Description, arg.RoleID)
}

const updateStatus_PATCH = `-- name: UpdateStatus_PATCH :execresult
UPDATE status SET name = COALESCE($1, name), description =  COALESCE($2, description), updated_at = NOW() WHERE  id_status = $3
`

type UpdateStatus_PATCHParams struct {
	Name        string
	Description sql.NullString
	IDStatus    int32
}

func (q *Queries) UpdateStatus_PATCH(ctx context.Context, arg UpdateStatus_PATCHParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateStatus_PATCH, arg.Name, arg.Description, arg.IDStatus)
}

const updateStatus_PUT = `-- name: UpdateStatus_PUT :execresult
UPDATE status SET name = $1, description = $2, updated_at = NOW() WHERE id_status = $3
`

type UpdateStatus_PUTParams struct {
	Name        string
	Description sql.NullString
	IDStatus    int32
}

func (q *Queries) UpdateStatus_PUT(ctx context.Context, arg UpdateStatus_PUTParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateStatus_PUT, arg.Name, arg.Description, arg.IDStatus)
}

const updateUserAvatar_PATCH = `-- name: UpdateUserAvatar_PATCH :exec
UPDATE "USER"
	SET avatar_url = $1,
		updated_at = NOW()
	WHERE uuid = $2
`

type UpdateUserAvatar_PATCHParams struct {
	AvatarUrl sql.NullString
	Uuid      string
}

func (q *Queries) UpdateUserAvatar_PATCH(ctx context.Context, arg UpdateUserAvatar_PATCHParams) error {
	_, err := q.db.ExecContext(ctx, updateUserAvatar_PATCH, arg.AvatarUrl, arg.Uuid)
	return err
}

const updateUserPassword_PATCH = `-- name: UpdateUserPassword_PATCH :exec
UPDATE "USER"
	SET password_hash = $1,
		updated_at = NOW()
	WHERE uuid = $2
`

type UpdateUserPassword_PATCHParams struct {
	PasswordHash string
	Uuid         string
}

func (q *Queries) UpdateUserPassword_PATCH(ctx context.Context, arg UpdateUserPassword_PATCHParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword_PATCH, arg.PasswordHash, arg.Uuid)
	return err
}

const updateUserRoleByUserID_PUT = `-- name: UpdateUserRoleByUserID_PUT :exec
UPDATE user_role SET role_id = $1 WHERE uuid = $2
`

type UpdateUserRoleByUserID_PUTParams struct {
	RoleID int32
	Uuid   string
}

func (q *Queries) UpdateUserRoleByUserID_PUT(ctx context.Context, arg UpdateUserRoleByUserID_PUTParams) error {
	_, err := q.db.ExecContext(ctx, updateUserRoleByUserID_PUT, arg.RoleID, arg.Uuid)
	return err
}

const updateUser_PATCH = `-- name: UpdateUser_PATCH :execresult
UPDATE "USER" 
	SET id_status = COALESCE($1, id_status), 
		user_name = COALESCE($2, user_name), 
		date_of_birth = COALESCE($3, date_of_birth), 
		email = COALESCE($4, email), 
		phone_num = COALESCE($5, phone_num), 
		address = COALESCE($6, address),
		updated_at = NOW() 
	WHERE uuid = $7
`

type UpdateUser_PATCHParams struct {
	IDStatus    sql.NullInt32
	UserName    string
	DateOfBirth sql.NullTime
	Email       string
	PhoneNum    sql.NullString
	Address     sql.NullString
	Uuid        string
}

func (q *Queries) UpdateUser_PATCH(ctx context.Context, arg UpdateUser_PATCHParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUser_PATCH,
		arg.IDStatus,
		arg.UserName,
		arg.DateOfBirth,
		arg.Email,
		arg.PhoneNum,
		arg.Address,
		arg.Uuid,
	)
}

const updateUser_PUT = `-- name: UpdateUser_PUT :execresult
UPDATE "USER" 
	SET id_status = $1, 
		user_name = $2, 
		date_of_birth = $3, 
		email = $4, phone_num = $5, address = $6 
	WHERE uuid = $7
`

type UpdateUser_PUTParams struct {
	IDStatus    sql.NullInt32
	UserName    string
	DateOfBirth sql.NullTime
	Email       string
	PhoneNum    sql.NullString
	Address     sql.NullString
	Uuid        string
}

func (q *Queries) UpdateUser_PUT(ctx context.Context, arg UpdateUser_PUTParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUser_PUT,
		arg.IDStatus,
		arg.UserName,
		arg.DateOfBirth,
		arg.Email,
		arg.PhoneNum,
		arg.Address,
		arg.Uuid,
	)
}

const userEmailExists = `-- name: UserEmailExists :one
SELECT EXISTS(SELECT 1 FROM "USER" WHERE email = $1)
`

func (q *Queries) UserEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRowContext(ctx, userEmailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userPhoneExists = `-- name: UserPhoneExists :one
SELECT EXISTS(SELECT 1 FROM "USER" WHERE phone_num = $1)
`

func (q *Queries) UserPhoneExists(ctx context.Context, phoneNum sql.NullString) (bool, error) {
	row := q.db.QueryRowContext(ctx, userPhoneExists, phoneNum)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
