// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_user.sql

package database

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO "user"(uuid, id_status, user_name, birth_date, email, phone_num, address, password_hash, avatar_url)
VALUES($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateUserParams struct {
	Uuid         string
	IDStatus     sql.NullInt32
	UserName     string
	BirthDate    sql.NullTime
	Email        string
	PhoneNum     sql.NullString
	Address      sql.NullString
	PasswordHash string
	AvatarUrl    sql.NullString
}

// _______________ Bảng User 4 ___________________
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.Uuid,
		arg.IDStatus,
		arg.UserName,
		arg.BirthDate,
		arg.Email,
		arg.PhoneNum,
		arg.Address,
		arg.PasswordHash,
		arg.AvatarUrl,
	)
	return err
}

const createUserRole = `-- name: CreateUserRole :exec
INSERT INTO user_role(uuid, role_id) VALUES($1, $2)
`

type CreateUserRoleParams struct {
	Uuid   string
	RoleID int32
}

// _______________ Bảng User-Roles 5 ___________________
func (q *Queries) CreateUserRole(ctx context.Context, arg CreateUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, createUserRole, arg.Uuid, arg.RoleID)
	return err
}

const deleteUser = `-- name: DeleteUser :execresult
DELETE FROM "user" WHERE uuid = $1
`

func (q *Queries) DeleteUser(ctx context.Context, uuid string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteUser, uuid)
}

const deleteUserRole = `-- name: DeleteUserRole :execresult
DELETE FROM user_role WHERE uuid = $1 AND role_id = $2
`

type DeleteUserRoleParams struct {
	Uuid   string
	RoleID int32
}

func (q *Queries) DeleteUserRole(ctx context.Context, arg DeleteUserRoleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteUserRole, arg.Uuid, arg.RoleID)
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT uuid, id_status, user_name, birth_date, email, phone_num, is_email_verified, is_phonenum_verified, address, password_hash, avatar_url, created_at, updated_at, deleted_at FROM "user"
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Uuid,
			&i.IDStatus,
			&i.UserName,
			&i.BirthDate,
			&i.Email,
			&i.PhoneNum,
			&i.IsEmailVerified,
			&i.IsPhonenumVerified,
			&i.Address,
			&i.PasswordHash,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRolesByUserID = `-- name: GetRolesByUserID :many
SELECT r.role_id, r.role_name, r.description
FROM "user" u 
	JOIN user_role ur ON u.uuid = ur.uuid 
	JOIN role r ON r.role_id = ur.role_id
	WHERE u.uuid = $1
`

func (q *Queries) GetRolesByUserID(ctx context.Context, uuid string) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, getRolesByUserID, uuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.RoleID, &i.RoleName, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUID_PasswordHashByEmail = `-- name: GetUID_PasswordHashByEmail :one
SELECT uuid, password_hash FROM "user" WHERE email = $1
`

type GetUID_PasswordHashByEmailRow struct {
	Uuid         string
	PasswordHash string
}

func (q *Queries) GetUID_PasswordHashByEmail(ctx context.Context, email string) (GetUID_PasswordHashByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUID_PasswordHashByEmail, email)
	var i GetUID_PasswordHashByEmailRow
	err := row.Scan(&i.Uuid, &i.PasswordHash)
	return i, err
}

const getUID_PasswordHashByPhone = `-- name: GetUID_PasswordHashByPhone :one
SELECT uuid, password_hash FROM "user" WHERE phone_num = $1
`

type GetUID_PasswordHashByPhoneRow struct {
	Uuid         string
	PasswordHash string
}

func (q *Queries) GetUID_PasswordHashByPhone(ctx context.Context, phoneNum sql.NullString) (GetUID_PasswordHashByPhoneRow, error) {
	row := q.db.QueryRowContext(ctx, getUID_PasswordHashByPhone, phoneNum)
	var i GetUID_PasswordHashByPhoneRow
	err := row.Scan(&i.Uuid, &i.PasswordHash)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT uuid, id_status, user_name, birth_date, email, phone_num, is_email_verified, is_phonenum_verified, address, password_hash, avatar_url, created_at, updated_at, deleted_at FROM "user" WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.IDStatus,
		&i.UserName,
		&i.BirthDate,
		&i.Email,
		&i.PhoneNum,
		&i.IsEmailVerified,
		&i.IsPhonenumVerified,
		&i.Address,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT uuid, id_status, user_name, birth_date, email, phone_num, is_email_verified, is_phonenum_verified, address, password_hash, avatar_url, created_at, updated_at, deleted_at FROM "user" WHERE uuid = $1
`

func (q *Queries) GetUserByID(ctx context.Context, uuid string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, uuid)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.IDStatus,
		&i.UserName,
		&i.BirthDate,
		&i.Email,
		&i.PhoneNum,
		&i.IsEmailVerified,
		&i.IsPhonenumVerified,
		&i.Address,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT uuid, id_status, user_name, birth_date, email, phone_num, is_email_verified, is_phonenum_verified, address, password_hash, avatar_url, created_at, updated_at, deleted_at FROM "user" WHERE phone_num = $1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phoneNum sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByPhone, phoneNum)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.IDStatus,
		&i.UserName,
		&i.BirthDate,
		&i.Email,
		&i.PhoneNum,
		&i.IsEmailVerified,
		&i.IsPhonenumVerified,
		&i.Address,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByRoleID = `-- name: GetUserByRoleID :many
SELECT u.uuid, u.user_name, u.email, u.phone_num, u.address
FROM "user" u 
	JOIN user_role ur ON u.uuid = ur.uuid 
	JOIN role r ON r.role_id = ur.role_id
	WHERE r.role_id = $1
`

type GetUserByRoleIDRow struct {
	Uuid     string
	UserName string
	Email    string
	PhoneNum sql.NullString
	Address  sql.NullString
}

func (q *Queries) GetUserByRoleID(ctx context.Context, roleID int32) ([]GetUserByRoleIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserByRoleID, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserByRoleIDRow
	for rows.Next() {
		var i GetUserByRoleIDRow
		if err := rows.Scan(
			&i.Uuid,
			&i.UserName,
			&i.Email,
			&i.PhoneNum,
			&i.Address,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserAvatar_PATCH = `-- name: UpdateUserAvatar_PATCH :execresult
UPDATE "user"
	SET avatar_url = $1,
		updated_at = NOW()
	WHERE uuid = $2
`

type UpdateUserAvatar_PATCHParams struct {
	AvatarUrl sql.NullString
	Uuid      string
}

func (q *Queries) UpdateUserAvatar_PATCH(ctx context.Context, arg UpdateUserAvatar_PATCHParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserAvatar_PATCH, arg.AvatarUrl, arg.Uuid)
}

const updateUserPassword_PATCH = `-- name: UpdateUserPassword_PATCH :execresult
UPDATE "user"
	SET password_hash = $1,
		updated_at = NOW()
	WHERE uuid = $2
`

type UpdateUserPassword_PATCHParams struct {
	PasswordHash string
	Uuid         string
}

func (q *Queries) UpdateUserPassword_PATCH(ctx context.Context, arg UpdateUserPassword_PATCHParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserPassword_PATCH, arg.PasswordHash, arg.Uuid)
}

const updateUserRoleByUserID_PUT = `-- name: UpdateUserRoleByUserID_PUT :execresult
UPDATE user_role SET role_id = $1 WHERE uuid = $2
`

type UpdateUserRoleByUserID_PUTParams struct {
	RoleID int32
	Uuid   string
}

func (q *Queries) UpdateUserRoleByUserID_PUT(ctx context.Context, arg UpdateUserRoleByUserID_PUTParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserRoleByUserID_PUT, arg.RoleID, arg.Uuid)
}

const updateUser_PATCH = `-- name: UpdateUser_PATCH :execresult
UPDATE "user" 
	SET id_status = COALESCE($1, id_status), 
		user_name = COALESCE($2, user_name), 
		birth_date = COALESCE($3, birth_date), 
		email = COALESCE($4, email), 
		phone_num = COALESCE($5, phone_num), 
		address = COALESCE($6, address),
		updated_at = NOW() 
	WHERE uuid = $7
`

type UpdateUser_PATCHParams struct {
	IDStatus  sql.NullInt32
	UserName  string
	BirthDate sql.NullTime
	Email     string
	PhoneNum  sql.NullString
	Address   sql.NullString
	Uuid      string
}

func (q *Queries) UpdateUser_PATCH(ctx context.Context, arg UpdateUser_PATCHParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUser_PATCH,
		arg.IDStatus,
		arg.UserName,
		arg.BirthDate,
		arg.Email,
		arg.PhoneNum,
		arg.Address,
		arg.Uuid,
	)
}

const updateUser_PUT = `-- name: UpdateUser_PUT :execresult
UPDATE "user" 
	SET id_status = $1, 
		user_name = $2, 
		birth_date = $3, 
		email = $4, phone_num = $5, address = $6 
	WHERE uuid = $7
`

type UpdateUser_PUTParams struct {
	IDStatus  sql.NullInt32
	UserName  string
	BirthDate sql.NullTime
	Email     string
	PhoneNum  sql.NullString
	Address   sql.NullString
	Uuid      string
}

func (q *Queries) UpdateUser_PUT(ctx context.Context, arg UpdateUser_PUTParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUser_PUT,
		arg.IDStatus,
		arg.UserName,
		arg.BirthDate,
		arg.Email,
		arg.PhoneNum,
		arg.Address,
		arg.Uuid,
	)
}
