// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package database

import (
	"context"
	"database/sql"
)

const createPermission = `-- name: CreatePermission :exec
INSERT INTO permissions(action_name, description) VALUES($1,$2) RETURNING action_id
`

type CreatePermissionParams struct {
	ActionName  string
	Description sql.NullString
}

// _______________ Bảng permissions 2 ___________________
func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) error {
	_, err := q.db.ExecContext(ctx, createPermission, arg.ActionName, arg.Description)
	return err
}

const createRole = `-- name: CreateRole :exec
INSERT INTO role(role_name,description) VALUES($1,$2) RETURNING role_id
`

type CreateRoleParams struct {
	RoleName    string
	Description sql.NullString
}

// _______________ Bảng Role 1 ___________________
func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) error {
	_, err := q.db.ExecContext(ctx, createRole, arg.RoleName, arg.Description)
	return err
}

const createRolePermission = `-- name: CreateRolePermission :exec
INSERT INTO role_permission(action_id, role_id) VALUES($1,$2)
`

type CreateRolePermissionParams struct {
	ActionID int32
	RoleID   int32
}

// _______________ Bảng Role_Permissions 3 ___________________
func (q *Queries) CreateRolePermission(ctx context.Context, arg CreateRolePermissionParams) error {
	_, err := q.db.ExecContext(ctx, createRolePermission, arg.ActionID, arg.RoleID)
	return err
}

const createStatus = `-- name: CreateStatus :exec

INSERT INTO status(name,description,updated_at,deleted_at) VALUES($1,$2,$3,$4) RETURNING id_status
`

type CreateStatusParams struct {
	Name        string
	Description sql.NullString
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

// // File: sql/queries.sql: tệp tin này chủ yếu chứa các câu lệnh thực thi
// _______________ Bảng Status 0 ___________________
func (q *Queries) CreateStatus(ctx context.Context, arg CreateStatusParams) error {
	_, err := q.db.ExecContext(ctx, createStatus,
		arg.Name,
		arg.Description,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const deletePermission = `-- name: DeletePermission :execresult
DELETE FROM permissions WHERE action_id = $1
`

func (q *Queries) DeletePermission(ctx context.Context, actionID int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deletePermission, actionID)
}

const deleteRole = `-- name: DeleteRole :execresult
DELETE FROM role WHERE role_id = $1
`

func (q *Queries) DeleteRole(ctx context.Context, roleID int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteRole, roleID)
}

const deleteRolePermission = `-- name: DeleteRolePermission :execresult
DELETE FROM role_permission WHERE action_id = $1 AND role_id = $2
`

type DeleteRolePermissionParams struct {
	ActionID int32
	RoleID   int32
}

func (q *Queries) DeleteRolePermission(ctx context.Context, arg DeleteRolePermissionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteRolePermission, arg.ActionID, arg.RoleID)
}

const deleteStatus = `-- name: DeleteStatus :execresult
DELETE FROM status WHERE id_status = $1
`

func (q *Queries) DeleteStatus(ctx context.Context, idStatus int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteStatus, idStatus)
}

const getAllPermissions = `-- name: GetAllPermissions :many
SELECT action_id, action_name, description, created_at, updated_at, deleted_at FROM permissions
`

func (q *Queries) GetAllPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, getAllPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ActionID,
			&i.ActionName,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllRoles = `-- name: GetAllRoles :many
SELECT role_id, role_name, description FROM role
`

func (q *Queries) GetAllRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, getAllRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.RoleID, &i.RoleName, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllStatus = `-- name: GetAllStatus :many
SELECT id_status, name, description, created_at, updated_at, deleted_at FROM status
`

func (q *Queries) GetAllStatus(ctx context.Context) ([]Status, error) {
	rows, err := q.db.QueryContext(ctx, getAllStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Status
	for rows.Next() {
		var i Status
		if err := rows.Scan(
			&i.IDStatus,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPermissionByID = `-- name: GetPermissionByID :one
SELECT action_id, action_name, description, created_at, updated_at, deleted_at FROM permissions WHERE action_id = $1
`

func (q *Queries) GetPermissionByID(ctx context.Context, actionID int32) (Permission, error) {
	row := q.db.QueryRowContext(ctx, getPermissionByID, actionID)
	var i Permission
	err := row.Scan(
		&i.ActionID,
		&i.ActionName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPermissionsByRoleID = `-- name: GetPermissionsByRoleID :many
SELECT p.action_id, p.action_name, p.description
FROM role r 
	INNER JOIN role_permission rp ON r.role_id = rp.role_id
	INNER JOIN permissions p ON p.action_id = rp.action_id
WHERE r.role_id = $1
`

type GetPermissionsByRoleIDRow struct {
	ActionID    int32
	ActionName  string
	Description sql.NullString
}

func (q *Queries) GetPermissionsByRoleID(ctx context.Context, roleID int32) ([]GetPermissionsByRoleIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getPermissionsByRoleID, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPermissionsByRoleIDRow
	for rows.Next() {
		var i GetPermissionsByRoleIDRow
		if err := rows.Scan(&i.ActionID, &i.ActionName, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT role_id, role_name, description FROM role WHERE role_id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, roleID int32) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByID, roleID)
	var i Role
	err := row.Scan(&i.RoleID, &i.RoleName, &i.Description)
	return i, err
}

const getRolesByPermissionID = `-- name: GetRolesByPermissionID :many
SELECT r.role_id, r.role_name, r.description
FROM role r 
	INNER JOIN role_permission rp ON r.role_id = rp.role_id
	INNER JOIN permissions p ON p.action_id = rp.action_id
WHERE p.action_id = $1
`

func (q *Queries) GetRolesByPermissionID(ctx context.Context, actionID int32) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, getRolesByPermissionID, actionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.RoleID, &i.RoleName, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatusByID = `-- name: GetStatusByID :one
SELECT id_status, name, description, created_at, updated_at, deleted_at FROM status WHERE id_status = $1
`

func (q *Queries) GetStatusByID(ctx context.Context, idStatus int32) (Status, error) {
	row := q.db.QueryRowContext(ctx, getStatusByID, idStatus)
	var i Status
	err := row.Scan(
		&i.IDStatus,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updatePermission_PATCH = `-- name: UpdatePermission_PATCH :execresult
UPDATE permissions SET 
	action_name = COALESCE($1, action_name), 
	description = COALESCE($2, description), 
	updated_at = NOW()
WHERE action_id = $3
`

type UpdatePermission_PATCHParams struct {
	ActionName  string
	Description sql.NullString
	ActionID    int32
}

func (q *Queries) UpdatePermission_PATCH(ctx context.Context, arg UpdatePermission_PATCHParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updatePermission_PATCH, arg.ActionName, arg.Description, arg.ActionID)
}

const updatePermission_PUT = `-- name: UpdatePermission_PUT :execresult
UPDATE permissions SET action_name = $1, description = $2, updated_at = NOW() WHERE action_id = $3
`

type UpdatePermission_PUTParams struct {
	ActionName  string
	Description sql.NullString
	ActionID    int32
}

func (q *Queries) UpdatePermission_PUT(ctx context.Context, arg UpdatePermission_PUTParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updatePermission_PUT, arg.ActionName, arg.Description, arg.ActionID)
}

const updateRolePermissionByRoleID_PUT = `-- name: UpdateRolePermissionByRoleID_PUT :execresult
UPDATE role_permission 
	SET action_id = $1, 
	role_id = $2,
	updated_at = NOW() 
WHERE action_id = $1 AND role_id = $2
`

type UpdateRolePermissionByRoleID_PUTParams struct {
	ActionID int32
	RoleID   int32
}

func (q *Queries) UpdateRolePermissionByRoleID_PUT(ctx context.Context, arg UpdateRolePermissionByRoleID_PUTParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateRolePermissionByRoleID_PUT, arg.ActionID, arg.RoleID)
}

const updateRole_PATCH = `-- name: UpdateRole_PATCH :execresult
UPDATE role SET role_name = COALESCE($1, role_name), description = COALESCE($2, description) WHERE role_id = $3
`

type UpdateRole_PATCHParams struct {
	RoleName    string
	Description sql.NullString
	RoleID      int32
}

func (q *Queries) UpdateRole_PATCH(ctx context.Context, arg UpdateRole_PATCHParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateRole_PATCH, arg.RoleName, arg.Description, arg.RoleID)
}

const updateRole_PUT = `-- name: UpdateRole_PUT :execresult
UPDATE role SET role_name = $1, description = $2 WHERE role_id = $3
`

type UpdateRole_PUTParams struct {
	RoleName    string
	Description sql.NullString
	RoleID      int32
}

func (q *Queries) UpdateRole_PUT(ctx context.Context, arg UpdateRole_PUTParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateRole_PUT, arg.RoleName, arg.Description, arg.RoleID)
}

const updateStatus_PATCH = `-- name: UpdateStatus_PATCH :execresult
UPDATE status SET name = COALESCE($1, name), description =  COALESCE($2, description), updated_at = NOW() WHERE  id_status = $3
`

type UpdateStatus_PATCHParams struct {
	Name        string
	Description sql.NullString
	IDStatus    int32
}

func (q *Queries) UpdateStatus_PATCH(ctx context.Context, arg UpdateStatus_PATCHParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateStatus_PATCH, arg.Name, arg.Description, arg.IDStatus)
}

const updateStatus_PUT = `-- name: UpdateStatus_PUT :execresult
UPDATE status SET name = $1, description = $2, updated_at = NOW() WHERE id_status = $3
`

type UpdateStatus_PUTParams struct {
	Name        string
	Description sql.NullString
	IDStatus    int32
}

func (q *Queries) UpdateStatus_PUT(ctx context.Context, arg UpdateStatus_PUTParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateStatus_PUT, arg.Name, arg.Description, arg.IDStatus)
}
