// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_verify.sql

package database

import (
	"context"
	"database/sql"
)

const userEmailExists = `-- name: UserEmailExists :one

SELECT EXISTS(SELECT 1 FROM "user" WHERE email = $1)
`

// _______ User Verification Queries _________
func (q *Queries) UserEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRowContext(ctx, userEmailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userEmailExists_HasNotBeenVerified = `-- name: UserEmailExists_HasNotBeenVerified :one
SELECT EXISTS(SELECT 1 FROM "user" WHERE email = $1 AND is_email_verified = FALSE)
`

func (q *Queries) UserEmailExists_HasNotBeenVerified(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRowContext(ctx, userEmailExists_HasNotBeenVerified, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userPhoneExists = `-- name: UserPhoneExists :one
SELECT EXISTS(SELECT 1 FROM "user" WHERE phone_num = $1)
`

func (q *Queries) UserPhoneExists(ctx context.Context, phoneNum sql.NullString) (bool, error) {
	row := q.db.QueryRowContext(ctx, userPhoneExists, phoneNum)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userPhoneExists_HasNotBeenVerified = `-- name: UserPhoneExists_HasNotBeenVerified :one
SELECT EXISTS(SELECT 1 FROM "user" WHERE phone_num = $1 AND is_phonenum_verified = FALSE)
`

func (q *Queries) UserPhoneExists_HasNotBeenVerified(ctx context.Context, phoneNum sql.NullString) (bool, error) {
	row := q.db.QueryRowContext(ctx, userPhoneExists_HasNotBeenVerified, phoneNum)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const verifyEmail = `-- name: VerifyEmail :execresult
UPDATE "user"
	SET is_email_verified = TRUE,
		updated_at = NOW()
	WHERE email = $1
`

func (q *Queries) VerifyEmail(ctx context.Context, email string) (sql.Result, error) {
	return q.db.ExecContext(ctx, verifyEmail, email)
}

const verifyPhone = `-- name: VerifyPhone :execresult
UPDATE "user"
	SET is_phonenum_verified = TRUE,
		updated_at = NOW()
	WHERE phone_num = $1
`

func (q *Queries) VerifyPhone(ctx context.Context, phoneNum sql.NullString) (sql.Result, error) {
	return q.db.ExecContext(ctx, verifyPhone, phoneNum)
}
