// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package database

import (
	"context"
	"database/sql"
)

const createPermission = `-- name: CreatePermission :exec
INSERT INTO permissions(action_name, description, updated_at, deleted_at) VALUES($1,$2,$3,$4) RETURNING action_id
`

type CreatePermissionParams struct {
	ActionName  string
	Description sql.NullString
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

// _______________ Bảng permissions 2 ___________________
func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) error {
	_, err := q.db.ExecContext(ctx, createPermission,
		arg.ActionName,
		arg.Description,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const createRole = `-- name: CreateRole :exec
INSERT INTO role(role_name,description) VALUES($1,$2) RETURNING role_id
`

type CreateRoleParams struct {
	RoleName    string
	Description sql.NullString
}

// _______________ Bảng Role 1 ___________________
func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) error {
	_, err := q.db.ExecContext(ctx, createRole, arg.RoleName, arg.Description)
	return err
}

const createStatus = `-- name: CreateStatus :exec

INSERT INTO status(name,description,updated_at,deleted_at) VALUES($1,$2,$3,$4) RETURNING id_status
`

type CreateStatusParams struct {
	Name        string
	Description sql.NullString
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

// // File: sql/queries.sql: tệp tin này chủ yếu chứa các câu lệnh thực thi
// _______________ Bảng Status 0 ___________________
func (q *Queries) CreateStatus(ctx context.Context, arg CreateStatusParams) error {
	_, err := q.db.ExecContext(ctx, createStatus,
		arg.Name,
		arg.Description,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const deletePermission = `-- name: DeletePermission :exec
DELETE FROM permissions WHERE action_id = $1
`

func (q *Queries) DeletePermission(ctx context.Context, actionID int32) error {
	_, err := q.db.ExecContext(ctx, deletePermission, actionID)
	return err
}

const deleteRole = `-- name: DeleteRole :execresult
DELETE FROM role WHERE role_id = $1
`

func (q *Queries) DeleteRole(ctx context.Context, roleID int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteRole, roleID)
}

const deleteStatus = `-- name: DeleteStatus :execresult
DELETE FROM status WHERE id_status = $1
`

func (q *Queries) DeleteStatus(ctx context.Context, idStatus int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteStatus, idStatus)
}

const getAllPermissions = `-- name: GetAllPermissions :many
SELECT action_id, action_name, description, created_at, updated_at, deleted_at FROM permissions
`

func (q *Queries) GetAllPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, getAllPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ActionID,
			&i.ActionName,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllRoles = `-- name: GetAllRoles :many
SELECT role_id, role_name, description FROM role
`

func (q *Queries) GetAllRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, getAllRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.RoleID, &i.RoleName, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllStatus = `-- name: GetAllStatus :many
SELECT id_status, name, description, created_at, updated_at, deleted_at FROM status
`

func (q *Queries) GetAllStatus(ctx context.Context) ([]Status, error) {
	rows, err := q.db.QueryContext(ctx, getAllStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Status
	for rows.Next() {
		var i Status
		if err := rows.Scan(
			&i.IDStatus,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPermissionByID = `-- name: GetPermissionByID :one
SELECT action_id, action_name, description, created_at, updated_at, deleted_at FROM permissions WHERE action_id = $1
`

func (q *Queries) GetPermissionByID(ctx context.Context, actionID int32) (Permission, error) {
	row := q.db.QueryRowContext(ctx, getPermissionByID, actionID)
	var i Permission
	err := row.Scan(
		&i.ActionID,
		&i.ActionName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT role_id, role_name, description FROM role WHERE role_id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, roleID int32) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByID, roleID)
	var i Role
	err := row.Scan(&i.RoleID, &i.RoleName, &i.Description)
	return i, err
}

const getStatusByID = `-- name: GetStatusByID :one
SELECT id_status, name, description, created_at, updated_at, deleted_at FROM status WHERE id_status = $1
`

func (q *Queries) GetStatusByID(ctx context.Context, idStatus int32) (Status, error) {
	row := q.db.QueryRowContext(ctx, getStatusByID, idStatus)
	var i Status
	err := row.Scan(
		&i.IDStatus,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updatePermission = `-- name: UpdatePermission :exec
UPDATE permissions SET action_name = $1, description = $2 WHERE action_id = $3
`

type UpdatePermissionParams struct {
	ActionName  string
	Description sql.NullString
	ActionID    int32
}

func (q *Queries) UpdatePermission(ctx context.Context, arg UpdatePermissionParams) error {
	_, err := q.db.ExecContext(ctx, updatePermission, arg.ActionName, arg.Description, arg.ActionID)
	return err
}

const updateRole = `-- name: UpdateRole :execresult
UPDATE role SET role_name = $1, description = $2 WHERE role_id = $3
`

type UpdateRoleParams struct {
	RoleName    string
	Description sql.NullString
	RoleID      int32
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateRole, arg.RoleName, arg.Description, arg.RoleID)
}

const updateStatus = `-- name: UpdateStatus :execresult
UPDATE status SET name = $1, description = $2, updated_at = $3 WHERE id_status = $4
`

type UpdateStatusParams struct {
	Name        string
	Description sql.NullString
	UpdatedAt   sql.NullTime
	IDStatus    int32
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateStatus,
		arg.Name,
		arg.Description,
		arg.UpdatedAt,
		arg.IDStatus,
	)
}
