// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/GiaBao0510/Ecommerce_golang/global"
	"github.com/GiaBao0510/Ecommerce_golang/internal/controller/http"
	"github.com/GiaBao0510/Ecommerce_golang/internal/controller/http/email"
	"github.com/GiaBao0510/Ecommerce_golang/internal/database"
	"github.com/GiaBao0510/Ecommerce_golang/internal/repository/repository_impl"
	"github.com/GiaBao0510/Ecommerce_golang/internal/service"
	"github.com/GiaBao0510/Ecommerce_golang/internal/service/authen"
	"github.com/GiaBao0510/Ecommerce_golang/internal/service/user"
	"github.com/GiaBao0510/Ecommerce_golang/pkg/loghelper"
	"github.com/mailjet/mailjet-apiv3-go"
	"go.uber.org/zap"
)

// Injectors from permission.wire.go:

func InitPermissionRouterHandler(db *database.Queries, logger *zap.Logger) (*http.PermissionController, error) {
	iPermissionRepository := repositoryimpl.NewPermissionRepository(db, logger)
	iPermissionService := service.NewPermissionService(iPermissionRepository, logger)
	permissionController := http.NewPermissionController(iPermissionService, logger)
	return permissionController, nil
}

// Injectors from role_permission.wire.go:

// KHởi tạo tiêm phụ thuộc cho RolesController
func InitRolePermissionRouterHandler(db *database.Queries, logger *zap.Logger) (*http.RolePermissionController, error) {
	iRolePermissionRepository := repositoryimpl.NewRolePermissionRepositoryImpl(db, logger)
	iRolePermissionService := service.NewRolePermissionService(iRolePermissionRepository, logger)
	rolePermissionController := http.NewRolePermissionController(iRolePermissionService, logger)
	return rolePermissionController, nil
}

// Injectors from roles.wire.go:

// Khởi tạo tiêm phụ thuộc cho RolesController
func InitRolesRouterHandler(db *database.Queries, logger *zap.Logger) (*http.RolesController, error) {
	iRolesRepository := repositoryimpl.NewRolesRepository(db, logger)
	iRolesService := service.NewRolesService(iRolesRepository, logger)
	rolesController := http.NewRolesController(iRolesService, logger)
	return rolesController, nil
}

// Injectors from status.wire.go:

func InitStatusRouterHandler(db *database.Queries, logger *zap.Logger) (*http.StatusController, error) {
	iStatusRepository := repositoryimpl.NewStatusRepository(db, logger)
	iStatusService := service.NewStatusService(iStatusRepository, logger)
	statusController := http.NewStatusController(iStatusService, logger)
	return statusController, nil
}

// Injectors from user.wire.go:

func InitUserRouterHandler(db *database.Queries, logger *zap.Logger) (*http.UserController, error) {
	iUserRepository := repositoryimpl.NewUserRepository(db, logger)
	iUserService := user.NewUserService(iUserRepository, logger)
	userController := http.NewUserController(iUserService, logger)
	return userController, nil
}

// Injectors from user_role.wire.go:

func InitUserRoleRouterHandler(db *database.Queries, logger *zap.Logger) (*http.UserRoleController, error) {
	iUserRoleRepository := repositoryimpl.NewUserRoleRepository(db, logger)
	iUserRoleService := user.NewUserRoleService(iUserRoleRepository, logger)
	userRoleController := http.NewUserRoleController(iUserRoleService, logger)
	return userRoleController, nil
}

// Injectors from verify.wire.go:

func InitVerifyRouterHandler(db *database.Queries, logger *zap.Logger) (email.EmailControllerInterface, error) {
	iUserRepository := repositoryimpl.NewUserRepository(db, logger)
	client := NewMailJectClient()
	dbLogger := NewDBLogger(logger)
	iEmailRepository := repositoryimpl.NewEmailRepositoryImpl(client, dbLogger)
	iRedisRepository := repositoryimpl.NewRedisRepositoryImpl(dbLogger)
	verifyUserUsecase := authen.NewVerifyUserUsecase(iUserRepository, iEmailRepository, iRedisRepository, dbLogger)
	emailControllerInterface := email.NewEmailController(verifyUserUsecase, dbLogger)
	return emailControllerInterface, nil
}

// verify.wire.go:

func NewDBLogger(logger *zap.Logger) *loghelper.DBLogger {
	return loghelper.NewDBLogger(logger, "VerifyFlow")
}

func NewMailJectClient() *mailjet.Client {
	return mailjet.NewMailjetClient(global.Config.
		Authentication.MailJet.API_key, global.Config.
		Authentication.MailJet.Secret_key,
	)
}
