// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/GiaBao0510/Ecommerce_golang/internal/controller"
	"github.com/GiaBao0510/Ecommerce_golang/internal/database"
	"github.com/GiaBao0510/Ecommerce_golang/internal/repository"
	"github.com/GiaBao0510/Ecommerce_golang/internal/repository/repository_impl"
	"github.com/GiaBao0510/Ecommerce_golang/internal/service"
	"go.uber.org/zap"
)

// Injectors from roles.wire.go:

// Khởi tạo tiêm phụ thuộc cho RolesController
func InitRolesRouterHandler(db *database.Queries, logger *zap.Logger) (*controller.RolesController, error) {
	iRolesRepository := repositoryimpl.NewRolesRepository(db, logger)
	iRolesService := service.NewRolesService(iRolesRepository)
	rolesController := controller.NewRolesController(iRolesService, logger)
	return rolesController, nil
}

// Injectors from status.wire.go:

func InitStatusRouterHandler(db *database.Queries, logger *zap.Logger) (*controller.StatusController, error) {
	iStatusRepository := repositoryimpl.NewStatusRepository(db, logger)
	iStatusService := service.NewStatusService(iStatusRepository)
	statusController := controller.NewStatusController(iStatusService, logger)
	return statusController, nil
}

// Injectors from user.wire.go:

func InitUserRouterHandler() (*controller.UserController, error) {
	iUserRepository := repository.NewUserRepository()
	iUserService := service.NewUserService(iUserRepository)
	userController := controller.NewUserController(iUserService)
	return userController, nil
}
