// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/GiaBao0510/Ecommerce_golang/internal/controller/http"
	"github.com/GiaBao0510/Ecommerce_golang/internal/database"
	"github.com/GiaBao0510/Ecommerce_golang/internal/repository/repository_impl"
	"github.com/GiaBao0510/Ecommerce_golang/internal/service"
	"go.uber.org/zap"
)

// Injectors from permission.wire.go:

func InitPermissionRouterHandler(db *database.Queries, logger *zap.Logger) (*http.PermissionController, error) {
	iPermissionRepository := repositoryimpl.NewPermissionRepository(db, logger)
	iPermissionService := service.NewPermissionService(iPermissionRepository, logger)
	permissionController := http.NewPermissionController(iPermissionService, logger)
	return permissionController, nil
}

// Injectors from role_permission.wire.go:

// KHởi tạo tiêm phụ thuộc cho RolesController
func InitRolePermissionRouterHandler(db *database.Queries, logger *zap.Logger) (*http.RolePermissionController, error) {
	iRolePermissionRepository := repositoryimpl.NewRolePermissionRepositoryImpl(db, logger)
	iRolePermissionService := service.NewRolePermissionService(iRolePermissionRepository, logger)
	rolePermissionController := http.NewRolePermissionController(iRolePermissionService, logger)
	return rolePermissionController, nil
}

// Injectors from roles.wire.go:

// Khởi tạo tiêm phụ thuộc cho RolesController
func InitRolesRouterHandler(db *database.Queries, logger *zap.Logger) (*http.RolesController, error) {
	iRolesRepository := repositoryimpl.NewRolesRepository(db, logger)
	iRolesService := service.NewRolesService(iRolesRepository, logger)
	rolesController := http.NewRolesController(iRolesService, logger)
	return rolesController, nil
}

// Injectors from status.wire.go:

func InitStatusRouterHandler(db *database.Queries, logger *zap.Logger) (*http.StatusController, error) {
	iStatusRepository := repositoryimpl.NewStatusRepository(db, logger)
	iStatusService := service.NewStatusService(iStatusRepository, logger)
	statusController := http.NewStatusController(iStatusService, logger)
	return statusController, nil
}

// Injectors from user.wire.go:

func InitUserRouterHandler(db *database.Queries, logger *zap.Logger) (*http.UserController, error) {
	iUserRepository := repositoryimpl.NewUserRepository(db, logger)
	iUserService := service.NewUserService(iUserRepository, logger)
	userController := http.NewUserController(iUserService, logger)
	return userController, nil
}
